---
id: Mime_Viewer
name: Mime_Viewer
full: MIME viewer library
description: A library that provides rendering drivers for MIME data.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Mime_Viewer
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Browser: ^2
      pear.horde.org/Horde_Compress: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Text_Filter: ^2
      pear.horde.org/Horde_Text_Flowed: ^2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_Translation: ^2.2
    ext:
      xml: '*'
  optional:
    pear:
      pear.php.net/Net_DNS2: '*'
